name: 'Azure Functions Build and Deploy'
# workflow based on reference implementation from: https://github.com/Azure-Samples/terraform-github-actions 

on:
  push:
    branches:
    - main
    paths:
    - src/**
    - .github/**
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - .github/**
  workflow_dispatch:  

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-app:
    name: 'Build C# app package for Azure Functions'
    runs-on: windows-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' 

      - name: 'Restore dependencies'
        run: dotnet restore azurefunction/azurefunction.csproj

      - name: 'Build project'
        run: dotnet build --configuration Release azurefunction/azurefunction.csproj

      - name: 'Publish project'
        run: dotnet publish --configuration Release --output ./publish azurefunction/azurefunction.csproj

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: azure-function-package
          path: ./publish

  deploy-app:
    name: 'Deploy Azure Functions to Function App'
    runs-on: windows-latest
    needs: [build-app]
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: azure-function-package
      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
